version: '3.7'
services:
        server:
                image: alextanhongpin/go-grace
                environment:
                        SERVER_HOST: 0.0.0.0
                        SERVER_PORT: 8080
                ports:
                        - 127.0.0.1:8080:8080
